org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
unityStreamingAssets=.unity3d, google-services-desktop.json, google-services.json, GoogleService-Info.plist
# As users of Unity 2022.3 are likely stuck on Gradle < 9, opt out
# of the new Android Gradle DSL (this will become a compile fail 
# in Gradle 10)
android.newDsl=false
# ... an opt out of built-in Kotlin support
android.builtInKotlin=false
