name: flutter_embed_unity
description: Harness the power of Unity 3D in your Flutter app by embedding Unity as a widget. Useful for adding 3D, gaming or augmented reality (AR) to your app.
version: 2.0.0
homepage: https://learntoflutter.com
repository: https://github.com/learntoflutter/flutter_embed_unity/tree/main/flutter_embed_unity
issue_tracker: https://github.com/learntoflutter/flutter_embed_unity/issues
documentation: https://github.com/learntoflutter/flutter_embed_unity/wiki
funding:
  - https://www.buymeacoffee.com/pPDtNs6A6T
topics:
  - unity

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_embed_unity_platform_interface: ^2.0.0
  # Only include 1 officially endorsed implementation for each platform!
  # Including multiple implementations can lead to some hard to debug problems
  # See https://github.com/learntoflutter/flutter_embed_unity/issues/54
  # e.g. only include either flutter_embed_unity_2022_3_android OR flutter_embed_unity_6000_0_android
  # The user can then override the default with a different implementation in their app's pubspec
  flutter_embed_unity_6000_0_android: #^2.0.0
    path: ../flutter_embed_unity_6000_0_android
  # flutter_embed_unity_2022_3_ios works for both Unity 2022.3 and Unity 6
  flutter_embed_unity_2022_3_ios: #^2.0.0
    path: ../flutter_embed_unity_2022_3_ios

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_embed_unity_6000_0_android
      ios:
        default_package: flutter_embed_unity_2022_3_ios
